---

- name: Ensure validate_password component is installed
  community.mysql.mysql_query:
    login_unix_socket: '{{ mysqld.socket }}'
    query: "INSTALL COMPONENT 'file://component_validate_password';"
  ignore_errors: true  # Can only activate once, prevent nasty errors if already active
